# Generated by Django 5.1.1 on 2024-10-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiradaCestaBasica',
            fields=[
                ('id_retira', models.AutoField(primary_key=True, serialize=False)),
                ('data_retira', models.DateField(auto_now_add=True)),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiario')),
            ],
        ),
    ]
