# Generated by Django 5.1.1 on 2024-10-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('retiradas_cestas_basicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retiradacestabasica',
            options={'ordering': ['-data_retira'], 'verbose_name': 'Retirada de Cesta Básica', 'verbose_name_plural': 'Retiradas de Cestas Básicas'},
        ),
        migrations.RemoveField(
            model_name='retiradacestabasica',
            name='id_beneficiario',
        ),
        migrations.AddField(
            model_name='retiradacestabasica',
            name='beneficiario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to='beneficiarios.beneficiario'),
        ),
    ]
