# Generated by Django 5.1.1 on 2024-10-20 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('retiradas_cestas_basicas', '0002_alter_retiradacestabasica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiradacestabasica',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to='beneficiarios.beneficiario'),
        ),
    ]
