# Generated by Django 5.1.1 on 2024-10-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('qtd_membros_familia', models.IntegerField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
